pipeline {
    agent any

    environment {
        DOCKER_IMAGE = 'spring-boot-app'
        APP_NAME = 'spring-boot-container'
    }

    stages {
		stage('Build Maven') {
			steps {
                dir('jenkins-spring-demo') {
                    sh 'chmod +x mvnw'
                    sh './mvnw clean package'
                }
            }
		}
        stage('Docker Build') {
            steps {
                dir('jenkins-spring-demo') {
                    sh "docker build -t ${DOCKER_IMAGE} ."
                }
            }
        }
        stage('Deploy'){
            steps {
                sh "docker rm -f ${APP_NAME} || true"
                sh "docker network create jenkins-demo-net || true"
                sh "docker run -d -p 8081:8080 --network jenkins-demo-net --name ${APP_NAME} ${DOCKER_IMAGE}"
            }
        }
    }
}